// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import {
//   Poppins,
//   Playfair_Display,
//   Work_Sans,
// } from "next/font/google";
// import "./globals.css";

// /* ================= Geist ================= */
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// /* ================= Poppins ================= */
// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: [
//     "100","200","300","400","500",
//     "600","700","800","900",
//   ],
//   variable: "--font-poppins",
//   display: "swap",
// });

// /* ================= Playfair ================= */
// const playfair = Playfair_Display({
//   subsets: ["latin"],
//   weight: ["400","500","600","700","800","900"],
//   variable: "--font-playfair",
//   display: "swap",
// });

// /* ================= Work Sans ================= */
// const worksans = Work_Sans({
//   subsets: ["latin"],
//   weight: [
//     "100","200","300","400","500",
//     "600","700","800","900",
//   ],
//   variable: "--font-worksans",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`
//           ${geistSans.variable}
//           ${geistMono.variable}
//           ${poppins.variable}
//           ${playfair.variable}
//           ${worksans.variable}
//           antialiased
//         `}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  Poppins,
  Playfair_Display,
  Work_Sans,
  Inter,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "./globals.css";

/* ================= Geist ================= */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* ================= Poppins ================= */
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-poppins",
  display: "swap",
});

/* ================= Playfair Display ================= */
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400","500","600","700","800","900"],
  variable: "--font-playfair",
  display: "swap",
});

/* ================= Work Sans ================= */
const worksans = Work_Sans({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-worksans",
  display: "swap",
});

/* ================= Inter ================= */
const inter = Inter({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-inter",
  display: "swap",
});

/* ================= Plus Jakarta Sans ================= */
const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800"],
  variable: "--font-plusjakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${poppins.variable}
          ${playfair.variable}
          ${worksans.variable}
          ${inter.variable}
          ${plusJakarta.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
