import type { Metadata } from "next";
import QueryProvider from "@/components/providers/QueryProvider";
import { Geist, Geist_Mono } from "next/font/google";
import {
  Poppins,
  Playfair_Display,
  Work_Sans,
  Inter,
  Plus_Jakarta_Sans,
  Manrope,
  Lato,
} from "next/font/google";
import "./globals.css";

/* ================= Geist ================= */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* ================= Poppins ================= */
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-poppins",
  display: "swap",
});

/* ================= Playfair Display ================= */
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400","500","600","700","800","900"],
  variable: "--font-playfair",
  display: "swap",
});

/* ================= Work Sans ================= */
const worksans = Work_Sans({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-worksans",
  display: "swap",
});

/* ================= Inter ================= */
const inter = Inter({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-inter",
  display: "swap",
});

/* ================= Plus Jakarta Sans ================= */
const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800"],
  variable: "--font-plusjakarta",
  display: "swap",
});

/* ================= Manrope ================= */
const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800"],
  variable: "--font-manrope",
  display: "swap",
});

/* ================= Lato ================= */
const lato = Lato({
  subsets: ["latin"],
  weight: ["100","300","400","700","900"],
  variable: "--font-lato",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${poppins.variable}
          ${playfair.variable}
          ${worksans.variable}
          ${inter.variable}
          ${plusJakarta.variable}
          ${manrope.variable}
          ${lato.variable}
          antialiased
        `}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
